name: Make content & deploy

on:
  page_build

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y fnt unoconv

      - name: Install fonts
        run: fnt update && fnt install google-merriweather fonts-open-sans

      - name: Make content
        run: make

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          emit_telemetry: false