name: Generate web content from sources

on:
  page_build

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y fnt unoconv

      - name: Install fonts
        run: fnt update && fnt install google-merriweather fonts-open-sans

      - name: Make content
        run: make

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}